export default{
    products: [
    {    _id:'1',
        name:'Jbl Speaker',
        category: 'Speakers',
        image: '/images/product-1.jpg',
        price: 70,
    brand: 'JBL',
rating:4.5,
numReviews:10,
countInStock: 6},
{    _id:'2',
name:'Seinnheiser',
category: 'Speakers',
image: '/images/product-1.jpg',
price: 70,
brand: 'JBL',
rating:4.5,
numReviews:10,
countInStock: 6},
{    _id:'3',
name:'Sony',
category: 'Speakers',
image: '/images/product-1.jpg',
price: 70,
brand: 'JBL',
rating:4.5,
numReviews:10,
countInStock: 6},
{    _id:'4',
name:'Bose',
category: 'Speakers',
image: '/images/product-1.jpg',
price: 70,
brand: 'JBL',
rating:4.5,
numReviews:10,
countInStock: 6},
{    _id:'5',
name:'Panasonic Speaker',
category: 'Speakers',
image: '/images/product-1.jpg',
price: 70,
brand: 'JBL',
rating:4.5,
numReviews:10,
countInStock: 6},
{    _id:'6',
name:'S Speaker',
category: 'Speakers',
image: '/images/product-1.jpg',
price: 70,
brand: 'JBL',
rating:4.5,
numReviews:10,
countInStock: 6},
    ]

}